# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stockMarket.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stockMarket.proto\x12\x0bstockMarket\"\"\n\rLookUpRequest\x12\x11\n\tstockName\x18\x01 \x01(\t\"6\n\x0eLookUpResponse\x12\x12\n\nstockPrice\x18\x01 \x01(\x01\x12\x10\n\x08stockVol\x18\x02 \x01(\x05\"K\n\x0cTradeRequest\x12\x11\n\tstockName\x18\x01 \x01(\t\x12\x15\n\rstockQuantity\x18\x02 \x01(\x05\x12\x11\n\tstockType\x18\x03 \x01(\t\"$\n\rTradeResponse\x12\x13\n\x0btradeStatus\x18\x01 \x01(\x05\"6\n\rUpdateRequest\x12\x11\n\tstockName\x18\x01 \x01(\t\x12\x12\n\nstockPrice\x18\x02 \x01(\x01\"&\n\x0eUpdateResponse\x12\x14\n\x0cupdateStatus\x18\x01 \x01(\x05\x32\xd9\x01\n\x0bStockMarket\x12\x43\n\x06LookUp\x12\x1a.stockMarket.LookUpRequest\x1a\x1b.stockMarket.LookUpResponse\"\x00\x12@\n\x05Trade\x12\x19.stockMarket.TradeRequest\x1a\x1a.stockMarket.TradeResponse\"\x00\x12\x43\n\x06Update\x12\x1a.stockMarket.UpdateRequest\x1a\x1b.stockMarket.UpdateResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stockMarket_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOOKUPREQUEST._serialized_start=34
  _LOOKUPREQUEST._serialized_end=68
  _LOOKUPRESPONSE._serialized_start=70
  _LOOKUPRESPONSE._serialized_end=124
  _TRADEREQUEST._serialized_start=126
  _TRADEREQUEST._serialized_end=201
  _TRADERESPONSE._serialized_start=203
  _TRADERESPONSE._serialized_end=239
  _UPDATEREQUEST._serialized_start=241
  _UPDATEREQUEST._serialized_end=295
  _UPDATERESPONSE._serialized_start=297
  _UPDATERESPONSE._serialized_end=335
  _STOCKMARKET._serialized_start=338
  _STOCKMARKET._serialized_end=555
# @@protoc_insertion_point(module_scope)
